storage:
  host: localhost
  port: 5432
  database: postgres
  username: postgres
  password: njxyj
  driverName: "postgres"

nats-server:
  host: "localhost"
  port: 4222
  cluster_id: "test-cluster"
  client_id: "test-client"
  channel: "testch"

http-server:
  host: "localhost"
  port: 8182